spring:
  datasource:
    url: "jdbc:mysql://192.168.2.101:3306/zhaomeng?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false"
    driver-class-name: com.mysql.jdbc.Driver
    username: "root"
    password: "root"
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql