#server:
#  port: 8082
#  servlet:
#    context-path: /hehe

#person:
#  name: super
#  age: 23
spring:
    profiles:
      active: dev
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.4.208:3306/ryx
#      connection-timeout: 50000
      password: zhaom
      data-username: zhaom
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
      database: mysql

name: super
age: 24
content: "姓名:${name},年龄:${age}}"