
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: "jdbc:mysql://192.168.4.208:3306/zhaomeng?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false"
      username: "root"
      password: "root"



mybatis:
  type-aliases-package: com..mm.demo.domain
  mapper-locations: classpath:mapper/*.xml
#  configuration: mybatis
#  type-handlers-package: #type handler处理包路径
#  check-config-location: false
#  executor-type: simple #执行模式  默认是simple

